// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-services.ts
var list_services_default = defineTool({
  name: "list_services",
  title: "List services",
  description: "List FilterPhone phone-filtering services (name, slug, price, category, description).",
  inputSchema: {
    category: z.string().trim().optional().describe("Optional category filter."),
    include_hidden: z.boolean().optional().describe("Include services hidden on the site (admins only).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, include_hidden }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("services").select("id, name, slug, price, category, short_desc, description, is_popular, visible, sort_order").order("sort_order", { ascending: true });
    if (!include_hidden) query = query.eq("visible", true);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { services: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_blog_posts_default = defineTool2({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List FilterPhone blog articles with title, slug, category and excerpt.",
  inputSchema: {
    search: z2.string().trim().optional().describe("Optional text to match in the title."),
    include_drafts: z2.boolean().optional().describe("Include unpublished drafts (admins only)."),
    limit: z2.number().int().optional().describe("Maximum number of posts to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, include_drafts, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const max = Math.min(Math.max(limit ?? 20, 1), 50);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("blog_posts").select("id, title, slug, category, excerpt, published, created_at, updated_at").order("created_at", { ascending: false }).limit(max);
    if (!include_drafts) query = query.eq("published", true);
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool3, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var get_blog_post_default = defineTool3({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch the full content of one FilterPhone blog article by its slug.",
  inputSchema: { slug: z3.string().trim().min(1).describe("Article slug, e.g. 'kosher-filtering'.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("blog_posts").select("*").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) throw new ToolError(`No blog post found with slug "${slug}".`);
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/get-site-settings.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_site_settings_default = defineTool4({
  name: "get_site_settings",
  title: "Get site settings",
  description: "Get FilterPhone site settings (contact details, business info, design keys) as key/value pairs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("site_settings").select("key, value");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const settings = {};
    (data ?? []).forEach((row) => {
      settings[row.key] = row.value;
    });
    return {
      content: [{ type: "text", text: JSON.stringify(settings) }],
      structuredContent: { settings }
    };
  }
});

// src/lib/mcp/tools/list-contact-submissions.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_contact_submissions_default = defineTool5({
  name: "list_contact_submissions",
  title: "List contact submissions",
  description: "List leads submitted through the FilterPhone contact forms. Requires an admin account.",
  inputSchema: {
    only_unread: z4.boolean().optional().describe("Return only submissions not yet marked as read."),
    limit: z4.number().int().optional().describe("Maximum submissions to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_unread, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const max = Math.min(Math.max(limit ?? 20, 1), 100);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("contact_submissions").select("id, name, phone, email, message, is_read, created_at").order("created_at", { ascending: false }).limit(max);
    if (only_unread) query = query.eq("is_read", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return {
        content: [
          {
            type: "text",
            text: "No submissions returned. This tool is limited to admin accounts."
          }
        ],
        structuredContent: { submissions: [] }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { submissions: data }
    };
  }
});

// src/lib/mcp/tools/mark-submission-read.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var mark_submission_read_default = defineTool6({
  name: "mark_submission_read",
  title: "Mark submission as read",
  description: "Mark one contact submission as read or unread. Requires an admin account.",
  inputSchema: {
    id: z5.string().trim().min(1).describe("Submission id."),
    is_read: z5.boolean().optional().describe("Read state to set (default true).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
  handler: async ({ id, is_read }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("contact_submissions").update({ is_read: is_read ?? true }).eq("id", id).select("id, name, is_read");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return {
        content: [
          { type: "text", text: "Nothing updated \u2014 the id was not found or you are not an admin." }
        ],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data[0]) }],
      structuredContent: { submission: data[0] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ofbpcavfltikvrmfsbku";
var mcp_default = defineMcp({
  name: "filterphone",
  title: "filterphone",
  version: "0.1.0",
  instructions: "Tools for FilterPhone, a phone-filtering service in Ashdod, Israel. Use `list_services` and `get_site_settings` for offering and contact details, `list_blog_posts`/`get_blog_post` for site content, and `list_contact_submissions`/`mark_submission_read` to review leads (admin accounts only).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_services_default,
    list_blog_posts_default,
    get_blog_post_default,
    get_site_settings_default,
    list_contact_submissions_default,
    mark_submission_read_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
